services:
    _defaults:
        autowire: true
        autoconfigure: true

    Guiziweb\SyliusShoppingAssistantPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    # AI Logger
    Psr\Log\LoggerInterface $aiLogger: '@monolog.logger.ai'

    # Tools - auto-tagged via ToolInterface autoconfigure

    # Chat Conversation Context - Composite
    guiziweb.context.chat_conversation.composite:
        class: Guiziweb\SyliusShoppingAssistantPlugin\Context\CompositeChatConversationContext
        public: true
